### ISSUE TITLE
Some Readmeness

### ISSUE THREAD

**Issue by ds0nt** [stevenmiller888/khaos-app#1]
I passed through, stared it, but never ran it:

You need some example:
- server code
- client code

And de-emphasis on the how to use a khaos generator. If I like the structure, I want it, If I see a big white terminal, I will take my chances on another boilerplate.

:) :dancer:

**Comment by stevenmiller888** [comment]
Great advice buddy. I'll update this with your ideas in mind when I get some free time. Happy to accept PRs :)
