### ISSUE TITLE
Babelify watchify vs duo-babel & duo-watch

### ISSUE THREAD

**Issue by ds0nt** [stevenmiller888/khaos-app#2]
Duo is meant to replace browserify.

Curious why you are doing it this way, and if it works better.

I have a project in which I have the three, although I am using only duo.

**Comment by stevenmiller888** [comment]
Sorry for the slow reply dude. Wasn't watching the repo. I think it depends on your use-case. When I made Keku I had been having some issues with Duo (mainly with it not picking up changes and the cache being too slow). But Dominic recently rewrote duo-cache from the ground-up and it works amazing now. So I might update this to use Duo :)
